# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "beacode"
client_id = "bfa086b61e00fc834d4986a0a8429f03"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
dev_store_url = "quickstart-83ebc71f.myshopify.com"
